import Link from 'next/link';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header>
          <h1>
            <Link href={'/'}>Scroll Sandbox</Link>
          </h1>
          <Link href={'/'}>Scroll Sandbox</Link> |{' '}
          <Link href={'/horizontal'}>Horizontal</Link> |{' '}
          <Link href={'/gsap'}>gsap</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
